global using ScenesTransitionSetupDataSO = ScenesTransitionSetupData;
global using StandardLevelScenesTransitionSetupDataSO = StandardLevelScenesTransitionSetupData;
global using MultiplayerLevelScenesTransitionSetupDataSO = MultiplayerLevelScenesTransitionSetupData;
global using MissionLevelScenesTransitionSetupDataSO = MissionLevelScenesTransitionSetupData;
